# Generated by Django 4.2.2 on 2023-06-22 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=45, null=True)),
                ('adresse', models.CharField(max_length=45, null=True)),
                ('telephone', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, null=True)),
                ('desscription', models.CharField(max_length=45, null=True)),
                ('prix', models.FloatField()),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.categorieproduit')),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.role')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.produit')),
            ],
        ),
        migrations.CreateModel(
            name='RoleDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.droit')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.role')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateField()),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.commande')),
            ],
        ),
        migrations.CreateModel(
            name='NoteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.CharField(max_length=45, null=True)),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prix', models.DateField()),
                ('prix', models.FloatField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.produit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateField()),
                ('commentaire', models.CharField(max_length=45, null=True)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField()),
                ('montant_total', models.FloatField()),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.commande')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.commande')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='id_fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur'),
        ),
    ]
