# Generated by Django 4.2.2 on 2023-06-30 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, null=True)),
                ('date_commande', models.DateField()),
                ('statut', models.CharField(choices=[('En attente de traitement', 'En Attente De Traitement'), ('En cours de traitement', 'En Cours De Traitement'), ('Livré à temps', 'Livré A Temps'), ('Livré en retard', 'Livré En Retard')], default='En Attente De Traitement', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField()),
                ('montant_total', models.FloatField()),
                ('numero_facture', models.IntegerField()),
                ('statut', models.CharField(choices=[('validé', 'Validé'), ('Non validé', 'Non Validé')], default='Non validé', max_length=100)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=45, null=True)),
                ('adresse', models.CharField(max_length=45, null=True)),
                ('telephone', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('prix', models.FloatField()),
                ('delais', models.CharField(max_length=45, null=True)),
                ('statut', models.CharField(choices=[('En précommande', 'En Précommande')], default='En Précommande', max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.categorieproduit')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.role')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('categorie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.categorieproduit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.produit')),
            ],
        ),
        migrations.CreateModel(
            name='RoleDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.droit')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.role')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(max_length=200, null=True)),
                ('numero_virement', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Non traité', 'Non Traité'), ('traité', 'Traité')], default='Non traité', max_length=100)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.commande')),
                ('facture', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.facture')),
            ],
        ),
        migrations.CreateModel(
            name='NoteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.CharField(max_length=200, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prix', models.DateField()),
                ('prix', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.produit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateField()),
                ('commentaire', models.CharField(max_length=200, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.commande')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur'),
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('prix_total', models.FloatField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur'),
        ),
    ]
