# Generated by Django 4.2.2 on 2023-06-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='id_fournisseur',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='detailcommande',
            old_name='id_commande',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='detailcommande',
            old_name='id_produit',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='id_commande',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='historiquecommande',
            old_name='id_commande',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='historiqueprix',
            old_name='id_produit',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='notefournisseur',
            old_name='id_fournisseur',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='id_commande',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='id_categorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='desscription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='id_fournisseur',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='id_produit',
            new_name='produit',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
