# Generated by Django 4.2.2 on 2023-06-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_paiement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
