# Generated by Django 4.2.2 on 2023-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_rename_id_fournisseur_commande_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
