# Generated by Django 4.2.2 on 2023-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_facture_numero_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieproduit',
            name='nom_categorie',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='droit',
            name='nom',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom_entreprise',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='numero_virement',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
