# Generated by Django 4.2.2 on 2023-06-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_commande_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcommande',
            name='prix_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='produit',
            name='delais',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='categorie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.categorieproduit'),
        ),
        migrations.AlterField(
            model_name='historiquecommande',
            name='commentaire',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notefournisseur',
            name='commentaire',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
