# Generated by Django 4.2.2 on 2023-07-08 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_categorieproduit_nom_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcommande',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.categorieproduit'),
        ),
    ]
