# Generated by Django 4.2.2 on 2023-06-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_detailcommande_prix_total_produit_delais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_facture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_virement',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
