# Generated by Django 4.2.2 on 2023-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_detailcommande_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
