# Generated by Django 4.2.2 on 2023-06-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_facture_fournisseur_facture_numero_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('rupture_de_stock', 'Rupture de stock')], default='Disponible', max_length=20),
        ),
    ]
