# Generated by Django 4.2.2 on 2023-08-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_commande_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='numero_virement',
        ),
    ]
