# Generated by Django 4.2.2 on 2023-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_produit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('En précommande', 'En Précommande'), ('disponible', 'Disponible'), ('rupture de stock', 'Rupture de stock')], default='En Précommande', max_length=20),
        ),
    ]
