# Generated by Django 4.2.2 on 2023-06-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_produit_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('En attente de traitement', 'En Attente De Traitement'), ('En cours de traitement', 'En Cours De Traitement'), ('Livré à temps', 'Livré A Temps'), ('Livré en retard', 'Livré En Retard')], default='En Attente De Traitement', max_length=100),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('validé', 'Validé'), ('Non validé', 'Non Validé')], default='Non Validé', max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='suppliers.facture'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('Non traité', 'Non Traité')], default='Non Traité', max_length=100),
        ),
    ]
