# Generated by Django 4.2.2 on 2023-06-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_commande_statut_facture_statut_paiement_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='suppliers.facture'),
        ),
    ]
