# Generated by Django 4.2.2 on 2023-06-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_alter_paiement_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcommande',
            name='prix_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.facture'),
        ),
    ]
