# Generated by Django 4.2.2 on 2023-06-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_alter_produit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='categorie',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.categorieproduit'),
        ),
    ]
