# Generated by Django 4.2.2 on 2023-06-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_alter_facture_fournisseur_alter_paiement_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(default='______', null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.fournisseur'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(default='_____', null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.facture'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='categorie',
            field=models.ForeignKey(default='_____', null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.categorieproduit'),
        ),
    ]
