# Generated by Django 4.2.2 on 2023-06-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_alter_facture_fournisseur_alter_paiement_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('Non traité', 'Non Traité')], default='Non traité', max_length=100),
        ),
    ]
