# Generated by Django 4.2.2 on 2023-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_alter_paiement_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('Non traité', 'Non Traité')], default=None, max_length=100),
        ),
    ]
