# Generated by Django 4.2.2 on 2023-06-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0019_alter_paiement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('validé', 'Validé'), ('Non validé', 'Non Validé')], default='Non validé', max_length=100),
        ),
    ]
