from .home import index
from .fournisseurs import *
from .categories_produits import *
from .produits import *
from .commandes import *
from .details_commandes import *
from .paiements import *
from .historiques_prix import *
from .stocks import *
from .factures import *
from .notes_fournisseurs import *
from .historiques_commandes import *
from .users import *